export enum AuditAction {
  VIEW_CONTACT = 'VIEW_CONTACT',
  DOWNLOAD_PDF = 'DOWNLOAD_PDF',
  CHANGE_VISIBILITY = 'CHANGE_VISIBILITY',
  VIEW_FINANCIALS = 'VIEW_FINANCIALS',
  EXPORT_DATA = 'EXPORT_DATA',
  DELETE_RECORD = 'DELETE_RECORD',
  CREATE_RECORD = 'CREATE_RECORD',
  UPDATE_RECORD = 'UPDATE_RECORD',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
}
